- id: 200
  key: satoshi
  currency: btc
  fixed: 8
  fee: 0.0004
  max: 0.1
  inuse: true
  type: WithdrawChannelSatoshi
- id: 400
  key: bank
  currency: brl
  fixed: 2
  fee_max: 0
  min: 9.99
  max: 2000
  fee: 9.00
  proportion: true
  inuse: true
  type: WithdrawChannelBank
- id: 600
  key: doge
  currency: doge
  fixed: 8
  max: 100000
  fee: 50.00
  inuse: true
  type: WithdrawChannelDoge
- id: 800
  key: ltc
  currency: ltc
  fixed: 8
  max: 20
  fee: 0.04
  inuse: true
  type: WithdrawChannelLtc
- id: 1000
  key: spero
  currency: spero
  fixed: 8
  max: 5000
  fee: 0.00
  inuse: true
  type: WithdrawChannelSpero
- id: 1200
  key: mxt
  currency: mxt
  fixed: 8
  max: 5000
  fee: 0.00
  inuse: true
  type: WithdrawChannelMxt
- id: 1400
  key: rvn
  currency: rvn
  fixed: 8
  max: 99999999999
  fee: 1
  inuse: true
  type: WithdrawChannelRvn
- id: 1600
  key: da
  currency: da
  fixed: 8
  max: 99999999999
  fee: 15
  inuse: true
  type: WithdrawChannelDa
- id: 1800
  key: ac
  currency: ac
  fixed: 8
  max: 99999999999
  fee: 5
  inuse: true
  type: WithdrawChannelAc
- id: 2000
  key: ep
  currency: ep
  fixed: 8
  max: 99999999999
  fee: 15
  inuse: true
  type: WithdrawChannelEp
- id: 2200
  key: ad
  currency: ad
  fixed: 8
  max: 99999999999
  fee: 5
  inuse: true
  type: WithdrawChannelAd
- id: 2400
  key: bd
  currency: bd
  fixed: 8
  max: 99999999999
  fee: 10
  inuse: true
  type: WithdrawChannelBd
- id: 2600
  key: hb
  currency: hb
  fixed: 8
  max: 99999999999
  fee: 10
  inuse: true
  type: WithdrawChannelHb
- id: 2800
  key: am
  currency: am
  fixed: 8
  max: 99999999999
  fee: 0.01
  inuse: true
  type: WithdrawChannelAm
- id: 3000
  key: at
  currency: at
  fixed: 8
  max: 99999999999
  fee: 1
  inuse: true
  type: WithdrawChannelAt
- id: 3200
  key: fz
  currency: fz
  fixed: 8
  max: 99999999999
  fee: 1
  inuse: true
  type: WithdrawChannelFz
- id: 3400
  key: ew
  currency: ew
  fixed: 8
  max: 99999999999
  fee: 0.5
  inuse: true
  type: WithdrawChannelEw
- id: 3600
  key: an
  currency: an
  fixed: 8
  max: 99999999999
  fee: 0.5
  inuse: true
  type: WithdrawChannelAn
- id: 3800
  key: fj
  currency: fj
  fixed: 8
  max: 99999999999
  fee: 0.01
  inuse: true
  type: WithdrawChannelFj
- id: 4000
  key: ba
  currency: ba
  fixed: 8
  max: 99999999999
  fee: 0.01
  inuse: true
  type: WithdrawChannelBa
- id: 4200
  key: et
  currency: et
  fixed: 8
  max: 99999999999
  fee: 1
  inuse: true
  type: WithdrawChannelEt
- id: 4400
  key: hv
  currency: hv
  fixed: 8
  max: 99999999999
  fee: 1
  inuse: true
  type: WithdrawChannelHv
- id: 4600
  key: gp
  currency: gp
  fixed: 8
  fee: 0.01
  inuse: true
  type: WithdrawChannelGp
